default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bokau_development
  host: localhost

test:
  <<: *default
  database: bokau_test
  host: localhost


production:
  <<: *default
  database: bokau_production
  username: bokau
  password: <%= ENV['BOKAU_DATABASE_PASSWORD'] %>
